name: Run Python Scripts

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering
  
jobs:
  run-scripts:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"  # Use Python 3.8

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run API_Fetch.py
        run: python API_Fetch.py

      - name: Run API_Fetch_Email.py
        run: python API_Fetch_Email.py
